[platformio]
default_envs = board_check

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

[env:board_check]
build_flags =
    -DSENSOR_ENABLED=0

[env:hcsr04]
build_flags =
    -DSENSOR_ENABLED=1
    -DSENSOR_COUNT=2
    -DSENSOR_START_INDEX=0
    -DTRIG_PIN_1=5
    -DECHO_PIN_1=18
    -DTRIG_PIN_2=19
    -DECHO_PIN_2=21

[env:hcsr04_sensor1]
build_flags =
    -DSENSOR_ENABLED=1
    -DSENSOR_COUNT=1
    -DSENSOR_START_INDEX=0
    -DTRIG_PIN_1=5
    -DECHO_PIN_1=18

[env:hcsr04_sensor2]
build_flags =
    -DSENSOR_ENABLED=1
    -DSENSOR_COUNT=1
    -DSENSOR_START_INDEX=1
    -DTRIG_PIN_2=19
    -DECHO_PIN_2=21
